# Generated by Django 5.1.1 on 2024-12-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_category_description_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_category',
            new_name='parent',
        ),
    ]
