# Generated by Django 5.1.1 on 2024-12-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_sub_category_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW'), ('Orange', 'Orange')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW'), ('Orange', 'Orange')], max_length=50, null=True),
        ),
    ]
