# Generated by Django 4.2.10 on 2025-01-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_due',
            field=models.FloatField(null=True),
        ),
    ]
