# Generated by Django 4.2.10 on 2025-01-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(blank=True, to='product.cartitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_paid',
            field=models.FloatField(null=True),
        ),
    ]
